### ISSUE TITLE
Raleway font

### ISSUE THREAD

**Issue by ankevanreeth** [lightspeeddevelopment/lsx#1]
The Raleway font from raleway_open_sans.css is overwriting all other styles. 
This can be adjusted by adding !important to child css, but it would be better to unregister or prevent it from loading in child functions.php.

**Comment by krugazul** [comment]
Hi Anke,  i did some testing,  ive updated the snippet below to include the lsx_font_scheme.  That also need to be excluded for the railway font to stop working.

There are reference to the font in app.css,  but those should default to the Open Sans font,

Also,  which site are you testing this on?  do you have a demo link?

```
add_action( 'wp_enqueue_scripts', 'lsx_child_remove_default_stylesheets', 20 );
function lsx_child_remove_default_stylesheets() {
    wp_dequeue_style( 'lsx-header-font' );
    wp_deregister_style( 'lsx-header-font' );
    wp_dequeue_style( 'lsx_font_scheme' );
    wp_deregister_style( 'lsx_font_scheme' );
}
```

**Comment by ankevanreeth** [comment]
Great! Worked fine.
