### ISSUE TITLE
503 Template needed for site deployments

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/lsx#10]
I got this information from this url: https://yoast.com/http-503-site-maintenance-seo/

They say you can create your own maintenance.php file by using the code from this url: http://queryposts.com/function/wp_maintenance/

If I do this, will the See You Later plugin use my maintenance.php file when I choose that option under "Look & Feel"? https://otjimbondona.feedmybeta.com/wp-admin/options-general.php?page=see-you-later&settings-updated=true

**Comment by nandotess** [comment]
I think this is not anymore necessary (create a custom maintenance template). This is not a feature from a WordPress theme, but from a WordPress plugin. We can use the See You later plugin from Woo or create a new option on LSX Customizer in future.
