### ISSUE TITLE
Adding Validation to LSX Customizer Settings

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx#106]
In WordPress 4.6 we will be able to add validation to customizer settings - https://make.wordpress.org/core/2016/07/05/customizer-apis-in-4-6-for-setting-validation-and-notifications/

Make LSX theme compatible with this new Customizer functionality.

**Comment by nandotess** [comment]
Resolved on LSX 2.0.0 branch.
