### ISSUE TITLE
Adding Selective Refresh in the LSX Customizer options

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx#107]
Currently a user needs to refresh the page manually to see customizer options and widgets, need to implement selective refresh:
- https://make.wordpress.org/core/2016/02/16/selective-refresh-in-the-customizer/
- https://make.wordpress.org/core/2016/03/22/implementing-selective-refresh-support-for-widgets/

**Comment by nandotess** [comment]
Resolved on LSX 2.0.0 branch.
