### ISSUE TITLE
Page template with basic masonry for grid layout

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/lsx#13]
- Example of functions can be found in Edin theme - http://wordpress.org/themes/edin/
- relevant page template is /page-templates/grid-page.php
- relevant template part is /content-grid.php
- relevant template tag functions can be found in /inc/template-tags.php
- attach suitable styling classes to the new page template & template part

**Comment by ashleyshaw** [comment]
No longer needed
