### ISSUE TITLE
Make it easy to customize Bootstrap options

### ISSUE THREAD

**Issue by justinwilson** [lightspeeddevelopment/lsx#138]
I'm trying to figure out the best way to alter the navbar breakpoint without adding a bunch of overriding css in the child theme I've set up. Is there a function or option somewhere that will allow me to change the breakpoint set at 1199px? It needs to change to a mobile menu much later (like 768px, or something like that).

I suggest adding a breakpoint option if there isn't one already, and perhaps other major Bootstrap options such as site colors (nav colors/backgrounds, link colors, buttons, etc).

I would also suggest giving full options for Google fonts since it only allows 3-4 of them.

**Comment by nandotess** [comment]
Hello @justinwilson.

1. About the first suggestion (breakpoint option), it's a good suggestion. I will schedule this for a future version. Thanks for share. [Issue opened](https://github.com/lightspeeddevelopment/lsx/issues/139).

2. About the second suggestion (customizer colours), we have an exclusive extension for the LSX that give you a full customisation of colours and blog structure: [LSX Customizer](https://www.lsdev.biz/product/lsx-site-customizer/).

3. About the third suggestion (Google Fonts), we already have this planned for the future. We will let you know when is implemented. Thanks for share. [Issue opened](https://github.com/lightspeeddevelopment/lsx/issues/140).

Thanks for use LSX. These feedbacks help us to keep improving our theme.

**Comment by justinwilson** [comment]
Thanks for the reply. The major question I have is how do I currently update the breakpoint? Is there a function or do I need to override it with a number of CSS changes in our child theme?

**Comment by nandotess** [comment]
Hello @justinwilson. Unfortunately the theme doesn't has an option to change the breakpoint. You will need to override the CSS using a child theme. Unfortunately we don't have the appropriated code to do this and send you. Sorry I can't help you more right now. But for sure we will implement your suggestion in one of the next versions.
