### ISSUE TITLE
Unable to activate Tour Operators Plugin

### ISSUE THREAD

**Issue by lmpage2** [lightspeeddevelopment/lsx#141]
Upon activation step, I receive error, "Tour Operator Plugin requires PHP 5.6 or higher."
I do have PHP 5.6 on Wordpress.org 4.71, but cannot get past the activation screen.
[TEMP.docx](https://github.com/lightspeeddevelopment/lsx/files/733146/TEMP.docx)

**Comment by nandotess** [comment]
Hello @lmpage2. Please, can you provide to us a screenshot from your `phpinfo()` content? We have tried to replicate this issue and we can't do it in our servers. Perhaps checking your server variables and informations we can discover the issue. Thanks.

**Comment by lmpage2** [comment]
Can you tell me where I can find this information on Wordpress.org?

**Comment by nandotess** [comment]
Hello @lmpage2. To help you, we have two questions:

1. Your website is hosted on Wordpress.org?

2. About the `phpinfo()` screenshot, please install [this](https://wordpress.org/plugins/wordpress-php-info/) plugin, access the plugin settings page and take a screenshot from it to send us.

Thanks.

**Comment by nandotess** [comment]
Hello @Impage2. Did you see our message? Did you find the solution? Let me know if we still can help you, thanks.

**Comment by lmpage2** [comment]
We ended up going a different direction.  Thanks anyway
