### ISSUE TITLE
Overriding WordPress Global Variables is not allowed

### ISSUE THREAD

**Issue by sakinshrestha** [lightspeeddevelopment/lsx#144]
* Overriding WordPress global Variables is not allowed. Check following files:
    * lsx-master/inc/comment-walker.php, line no 17,  23,  29 and 30
    * lsx-master/inc/jetpack.php, line no 63 and 64

**Comment by krugazul** [comment]
I have changed this code, it no longer overwrites the global WP variables.
https://github.com/lightspeeddevelopment/lsx/commit/167ce87c5a9e66a6eea9b59a88dde467086b4820
