### ISSUE TITLE
License Issues:

### ISSUE THREAD

**Issue by sakinshrestha** [lightspeeddevelopment/lsx#146]
* Proper license and attribution of resources used by theme not found. Theme must add attribution and license of all the resources like: javascripts, fonts, css and bundled images used in its readme file
 * Go to this link: https://make.wordpress.org/themes/2014/07/08/proper-copyrightlicense-attribution-for-themes/ to know more about Proper license and attribution

**Comment by justintadlock** [comment]
Note that the Font Awesome CSS (included in theme) is licensed under the MIT.  It's the font that's under the SIL OFL.  So, you'll want to mention both in your Resources section of the readme.

**Comment by nandotess** [comment]
Resolved on LSX 2.0.0 branch.
