### ISSUE TITLE
For WordPress.org

### ISSUE THREAD

**Issue by sakinshrestha** [lightspeeddevelopment/lsx#147]
* Ignore this issue, if you are not planning to submit theme in Wordpress.org
* If you are a theme shop, you should be selling under GPL to be in the WordPress.org repo. For explanation see this link: https://make.wordpress.org/themes/2015/08/15/themes-should-be-100-gpl/
 * I did not find any license clarification in your Theme URL and Author URL
* Remove LSX page from admin bar it looks like lots of advertisement, themes are allowed to add a page but it should have information only related to theme. It will not be allowed in WordPress.org

**Comment by nandotess** [comment]
Hello, @sakinshrestha.

Thanks for your help. Actually, **LSX** is under **GPL** licence. This info is available on:
- README.md file;
- LICENSE file;
- package.json file;
- style.css file;
- GitHub repo info.

Can you clarify what we need to fix? Thanks!

_Note: please check the v2.0.0 repository._

**Comment by krugazul** [comment]
Im closing this issue,  they have been resolved and the theme is on WP.org.
