### ISSUE TITLE
Loading google fonts

### ISSUE THREAD

**Issue by sakinshrestha** [lightspeeddevelopment/lsx#148]
* All stylesheets must be registered/enqueued via `wp_enqueue_style`
* Check `inc/google-font-collection.php`, line no 111
* Proper way of adding google font is here: https://themeshaper.com/2014/08/13/how-to-add-google-fonts-to-wordpress-themes/

**Comment by nandotess** [comment]
LSX 2.0: we will remove the Google Fonts CDN and will store the Google Fonts in theme (performance issues with Google CDN in some countries). This issue will be automatically fixed.
