### ISSUE TITLE
Singluar Placeholders Issue

### ISSUE THREAD

**Issue by sakinshrestha** [lightspeeddevelopment/lsx#149]
* Check `comments.php`,  line no 30 and `content.php` line no 133
* Missing singular placeholder, needed for some languages. See https://codex.wordpress.org/I18n_for_WordPress_Developers#Plurals
* This issue is fixed in twentyseventeen: https://github.com/WordPress/twentyseventeen/blob/master/comments.php#L32-L50

**Comment by nandotess** [comment]
Resolved on LSX 2.0.0 branch.
