### ISSUE TITLE
Plugin Territory: Disabling wpautop on excerpts

### ISSUE THREAD

**Issue by sakinshrestha** [lightspeeddevelopment/lsx#152]
* In `inc/extras.php` line no 421: `remove_filter( 'the_excerpt', 'wpautop' );`, this removes <p> tags from excerpts
* This falls under plugin territory as if user switches the theme, this functionality goes away

**Comment by ashleyshaw** [comment]
@nandotess we should move this to our site customizer extension or other suitable extension.

**Comment by justintadlock** [comment]
It's not just the removal of `wpautop`.  This bit of code from `inc/extras.php` is plugin territory too.

```
remove_filter('get_the_excerpt', 'wp_trim_excerpt');
add_filter('get_the_excerpt', 'wpse_custom_wp_trim_excerpt');
```

I noticed this because the custom filter is actually breaking HTML in at least one case (and probably more) with an auto-generated excerpt.  Here's some test content I was using:

```
Nested and mixed lists are an interesting beast. It's a corner case to make sure that
<ul>
	<li>Lists within lists do not break the ordered list numbering order.</li>
	<li>Your list styles go deep enough.</li>
</ul>
<h3>Ordered - Unordered - Ordered</h3>
<ol>
	<li>ordered item</li>
	<li>ordered item
<ul>
	<li><strong>unordered</strong></li>
	<li><strong>unordered</strong>
<ol>
	<li>ordered item</li>
	<li>ordered item</li>
</ol>
</li>
</ul>
</li>
	<li>ordered item</li>
	<li>ordered item</li>
</ol>
```

**Comment by nandotess** [comment]
We will move this to LSX Customizer extension.

**Comment by krugazul** [comment]
This has been removed - https://github.com/lightspeeddevelopment/lsx/commit/d9cbdc08f63dde55fcd8de043727d4bd3ac35d44
