### ISSUE TITLE
Plugin Territory: Allowing extra img attributes

### ISSUE THREAD

**Issue by sakinshrestha** [lightspeeddevelopment/lsx#154]
* In `inc/extras.php` and `lazyload.php` function `lsx_kses_allowed_html`, extra img atributes are allowed
* If user changes the theme, this data will be lost, hence, this falls under plugin territory

**Comment by ashleyshaw** [comment]
@nandotess we should move this to the site customizer plugin.

**Comment by nandotess** [comment]
We will move this to LSX Customizer extension.

**Comment by krugazul** [comment]
This function wont be moved into the plugin.    It is allowing html attributes to show.   The attributes are **not** added via the Dashboard, and are specific to this theme.   So if a user changes the theme, no information is lost.

The srcset and sizes attributes use WordPress Data to generate a range of image sizes.
