### ISSUE TITLE
Sanitizing email output

### ISSUE THREAD

**Issue by sakinshrestha** [lightspeeddevelopment/lsx#159]
* Use `antispambot()` function along with `esc_html` for sanitizing emails on output
* `header.php`, line no 70 becomes:
`<span class="email-address"><?php esc_html_e( 'Questions? Email Us: ', 'lsx' ); ?><a href="mailto:<?php echo esc_attr( antispambot( $email_address ) ); ?>"><?php echo esc_html( antispambot( $email_address ) ); ?></a></span>`

**Comment by nandotess** [comment]
Resolved on LSX 2.0.0 branch.
