### ISSUE TITLE
Test third level main menu dropdowns

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/lsx#16]
Make sure they display well, if there is an issue then log in github issues

**Comment by themeticus** [comment]
Third-level menus do not work correctly when set via Appearance > Menus for desktop or mobile viewports. Only 1st and 2nd-level menu items render on the front end

**Comment by rafisegerman** [comment]
I have added support for third-level menu dropdowns in the shop branch: https://github.com/lightspeeddevelopment/lsx/blob/shop/inc/template-tags.php#L391
