### ISSUE TITLE
Escaping url

### ISSUE THREAD

**Issue by sakinshrestha** [lightspeeddevelopment/lsx#161]
* Escape following links using `esc_url()` before output
    * `extras.php`, line no 408, 459 `get_permalink()`
    * `template-tags.php`, line no 157 `get_category_link( $cat->term_id )`
    * `the-events-calendar.php`, line no 40, 49, 60, 63 `get_post_type_archive_link( 'tribe_events' )`
    * `wp-bootstrap-navwalker.php` line no 209 `admin_url( 'nav-menus.php' )`
* Escape following image src/srcset using esc_url() before output
    * `extras.php` function `lsx_get_thumbnail()`, `$img` in lines 229, 231

**Comment by nandotess** [comment]
Resolved on LSX 2.0.0 branch.
