### ISSUE TITLE
Implement comments in pages properly

### ISSUE THREAD

**Issue by sakinshrestha** [lightspeeddevelopment/lsx#162]
* Comment missing in page. Page should support comment. At least user should have option to enable comment. 
* Currently, no comments are being shown on pages

**Comment by ashleyshaw** [comment]
@nandotess by default WP disables comments on pages, there might be a need for an end user to enable page specific comments, so we should add support to the template.

**Comment by justintadlock** [comment]
This filter in `inc/config.php` should go too: `lsx_page_comments_off()`.  Themes shouldn't be auto-disabling page comments.

**Comment by nandotess** [comment]
Resolved on LSX 2.0.0 branch.
