### ISSUE TITLE
Question: Defering JS

### ISSUE THREAD

**Issue by sakinshrestha** [lightspeeddevelopment/lsx#163]
* In `scripts.php` lines 102-118, you have added defer to jquery
* `clean_url` is depreciated
* Does this code have any significant value in newer browsers?

**Comment by justintadlock** [comment]
The `clean_url` filter hook is not deprecated (the function is).  It's executed any time `esc_url()` is called.  However, themes really shouldn't be adding filters to it.  Generally, I'd say that'd be plugin territory.

I don't think this would be the appropriate filter anyway.  There's probably a filter that's more specific to scripts.

**Comment by nandotess** [comment]
Resolved on LSX 2.0.0 branch.
