### ISSUE TITLE
More Design Issues

### ISSUE THREAD

**Issue by sakinshrestha** [lightspeeddevelopment/lsx#165]
* Bullet points goes outside wrapper in archive pages. See this 
![bullet-ponts-outside-wrapper](https://cloud.githubusercontent.com/assets/9452203/23824629/e9816fee-06a1-11e7-8aa5-b8bfc99d9c33.png)
* Post meta, alignment issue. See this
![commen-meta-post-alignment](https://cloud.githubusercontent.com/assets/9452203/23824630/e9828c76-06a1-11e7-978e-5b4f09ac9370.png)
* Extra wide image is stretching and you need add height: auto; in css
![extra-wide-image](https://cloud.githubusercontent.com/assets/9452203/23824645/28e0f9c0-06a2-11e7-8179-c8042721fa16.png)

**Comment by ashleyshaw** [comment]
@nandotess we need to review this issue along with the blog customizer compatibility.

**Comment by fmdalpiaz** [comment]
Resolved on LSX 2.0.0 branch.
