### ISSUE TITLE
Page name blog have issues

### ISSUE THREAD

**Issue by sakinshrestha** [lightspeeddevelopment/lsx#166]
* When I create page name "Blog" there is, two title called "Blog" also have border and space issue. 
* Second title is coming from function `lsx_blog_header` in `layout.php` file. Please check in. 
![page-blog](https://cloud.githubusercontent.com/assets/9452203/23830184/b27cb752-072c-11e7-8b45-4b52cfd0fcc5.png)

**Comment by ashleyshaw** [comment]
@nandotess please investigate, if this is easy to resolve, please bundle the fix into milestone 1.8.5

**Comment by nandotess** [comment]
Resolved on LSX 2.0.0 branch.
