### ISSUE TITLE
Two headers

### ISSUE THREAD

**Issue by justintadlock** [lightspeeddevelopment/lsx#169]
I'd break up `header.php` into `header.php` and `header-landing.php`.  

Then, in `singular.php`, add this bit of code:

```
is_singular( 'landing-page' ) ? get_header( 'landing' ) : get_header(); ?>
```

Personally, I'm more of a fan of separating the code into their own templates than using conditionals to separate large bits of code within templates.  Plus, there's always the added benefit of child themes being able to overwrite just the header for the landing page.

**Comment by nandotess** [comment]
Resolved on LSX 2.0.0 branch.
