### ISSUE TITLE
Core pagination

### ISSUE THREAD

**Issue by justintadlock** [lightspeeddevelopment/lsx#170]
Now that core WP has had a built-in pagination function for several releases, it might be time to drop support for the old WP PageNavi plugin.  If you still wanted to offer users a choice between pagination and prev/next links, you could do that via a customizer option.

See: https://developer.wordpress.org/reference/functions/the_posts_pagination/

**Comment by nandotess** [comment]
Resolved on LSX 2.0.0 branch.
