### ISSUE TITLE
Translator notes vs. Translator context

### ISSUE THREAD

**Issue by justintadlock** [lightspeeddevelopment/lsx#171]
In `template-tags.php`, I see internationalized text like so, using the "context" function:

```
esc_html_x( 'Posted on:', 'Used before publish date.', 'lsx' ),
```

And this:

```
esc_html_x( 'Posted by:', 'Used before post author name.', 'lsx' ),
```

What you really should be doing is called translator notes rather than using the context (i.e., `_x()` function).  So, those function calls should look like this:

```
// Translators: Used before publish date.
esc_html__( 'Posted on:', 'lsx' ),

// Translators: Used before post author name.
esc_html__( 'Posted by:', 'lsx' ),
```

The core WP i18n tool will pick up these translator notes and add them to the POT file automatically.

While your code is not "broken", exactly, I wouldn't say it's used correctly.  The `_x()` function should be used in a situation like:

```
_x( 'Post', 'noun', 'lsx' )

_x( 'Post', 'verb', 'lsx' )
```

This is when you have one text string with different meanings.  You add a context because users in another language will likely need two different translations.

**Comment by nandotess** [comment]
Resolved on LSX 2.0.0 branch.
