### ISSUE TITLE
Use has_nav_menu()

### ISSUE THREAD

**Issue by justintadlock** [lightspeeddevelopment/lsx#173]
In the `lsx_navbar_header()` and `lsx_nav_menu()` functions in `inc/template-tags.php`, you should use the `has_nav_menu()` core function for checking if there's a menu assigned to that nav menu location.

This bit of code:

```
if(false != $nav_menu && isset($nav_menu['primary']) && 0 != $nav_menu['primary']){ ?>
```

Should be:

```
if ( has_nav_menu( 'primary' ) ) { ?>
```

See: https://developer.wordpress.org/reference/functions/has_nav_menu/

**Comment by nandotess** [comment]
Resolved on LSX 2.0.0 branch.
