### ISSUE TITLE
Function call instead of shortcode

### ISSUE THREAD

**Issue by justintadlock** [lightspeeddevelopment/lsx#174]
In the `lsx_footer_subscription_cta()` function in `inc/template-tags.php`, this call to the shortcode should be a direct function call:

```
<?php echo do_shortcode( '[caldera_form id="'.$subscribe_form_id.'"]' ); ?>
```

What I mean is that plugins should have an actual function to call, such as:

```
function caldera_some_function() {}
```

Calling the function directly instead of `do_shortcode()` is preferable because shortcodes require parsing and are not as fast.  Plus, you're already writing PHP here, so there's no need to switch to the shortcode.

Your code should look something like:

```
<?php echo caldera_some_function( array( 'id' => $subscribe_form_id ) ); ?>
```

I'm not familiar with the plugin, but I'd imagine it'd have a function you can access directly.  It should anyway.

**Comment by nandotess** [comment]
Done: https://github.com/lightspeeddevelopment/lsx/pull/184
