### ISSUE TITLE
Page number in lsx_wp_title()

### ISSUE THREAD

**Issue by justintadlock** [lightspeeddevelopment/lsx#176]
In the `lsx_wp_title()` function in `inc/extras.php`, I'd run `intval()` over `$page` and `$paged` to be on the safe side.  There was a big security issues with that a year or so back where several theme authors were contacted about making sure those were in fact integers.

```
if ( $paged >= 2 || $page >= 2 ) {
	$title .= " $sep " . sprintf( __( 'Page %s', 'lsx' ), max( $paged, $page ) );
}
```

**Comment by nandotess** [comment]
Resolved on LSX 2.0.0 branch.
