### ISSUE TITLE
Archive title and description

### ISSUE THREAD

**Issue by justintadlock** [lightspeeddevelopment/lsx#177]
This is in reference to the `lsx_global_header()` function in `inc/layout.php`

For archive descriptions, you should use the core `the_archive_description()` function instead of `term_description()` on lines 211 and 225.  You should do the same for the author description on line 203.

You'll want to use this function in case plugins filter the output.  If you want to change the output on your own, you can use `get_the_archive_description` filter hook: https://developer.wordpress.org/reference/hooks/get_the_archive_description/

For the author title and WooCommerce archive title, you should use `the_archive_title()` on lines 199 and 210.  This is for the same reason.  Use the `get_the_archive_title` filter hook if you want to overwrite it: https://developer.wordpress.org/reference/hooks/get_the_archive_title/

On line 219, you should use the `$before` parameter.  This:

```
Type: <?php the_archive_title(); ?>
```

Should look like (also, make sure it can be translated):

```
<?php the_archive_title( __( 'Type:', 'lsx' ) ); ?>
```

**Comment by nandotess** [comment]
Resolved on LSX 2.0.0 branch.
