### ISSUE TITLE
Styling: Lists in comments

### ISSUE THREAD

**Issue by justintadlock** [lightspeeddevelopment/lsx#178]
When an `<ul>` list is used in the comment text, there are no bullet points.  Also, nested lists are not indented. 

![lists-comment-text](https://cloud.githubusercontent.com/assets/1816309/23919610/6f24a9ca-08c5-11e7-954c-da38e1603615.png)

**Comment by fmdalpiaz** [comment]
Resolved on LSX 2.0.0 branch.

![lists](https://cloud.githubusercontent.com/assets/2198427/26429799/7e6a46e2-40bf-11e7-9da7-1fc3f4650da7.png)
