### ISSUE TITLE
"Continue Reading" on attachments

### ISSUE THREAD

**Issue by justintadlock** [lightspeeddevelopment/lsx#179]
There's an errant "Continue Reading" link on singular attachment pages.  It looks like it's being output as part of the image caption.

![attachment-continue](https://cloud.githubusercontent.com/assets/1816309/23919723/fa171d6a-08c5-11e7-8773-1c1ae1145910.png)

**Comment by nandotess** [comment]
Resolved on LSX 2.0.0 branch.
