### ISSUE TITLE
Styling: Gallery item border

### ISSUE THREAD

**Issue by justintadlock** [lightspeeddevelopment/lsx#180]
There's a gray bottom border under each of your gallery items.  I'm guessing this is not intentional.  It looks to be coming from this code in your CSS:

```
dl dt {
    margin-top: 15px;
    margin-bottom: 6px;
    padding-bottom: 3px;
    border-bottom: 1px solid #ddd;
}
```

![gallery](https://cloud.githubusercontent.com/assets/1816309/23919825/672950da-08c6-11e7-899c-048199530c91.png)

**Comment by fmdalpiaz** [comment]
Resolved on LSX 2.0.0 branch.
