### ISSUE TITLE
Plugin territory and Jetpack integration

### ISSUE THREAD

**Issue by justintadlock** [lightspeeddevelopment/lsx#181]
Some of the features you've added when Jetpack is active would be considered plugin territory.

The "Client" and "Web Site" metadata will be lost when a users switches themes.  

If you don't mind a little shameless, self-promotion from me, might I recommend the [Custom Content Portfolio plugin](https://wordpress.org/plugins/custom-content-portfolio/) (it has these fields built in)?  It's an alternative to consider anyway.

------

This filter in `inc/jetpack.php` would also be considered plugin territory:

```
add_filter( 'rest_api_allowed_post_types', 'lsx_allowed_related_post_types' );
```

Themes shouldn't really register things like this because the user loses this when they switch themes.

**Comment by nandotess** [comment]
Temporarily (on LSX 2.0) we removed all external plugins integrations (Jetpack, WooCommerce, Sensei, ...). We will move the integrations to an extension and will test all again.
