### ISSUE TITLE
wp_footer() should be called last

### ISSUE THREAD

**Issue by justintadlock** [lightspeeddevelopment/lsx#182]
In `footer.php`, the `wp_footer()` call should be executed last, just before the closing `</body>` tag.  Currently, the theme calls it before the `lsx_body_bottom()` function is executed.

In the .ORG theme repo, we require this because not doing it often leads to users or plugins breaking things.  For example, a child theme author might hook into `lsx_body_bottom` to output something, which ends up wrecking some other output, such as the admin bar.

**Comment by nandotess** [comment]
Resolved on LSX 2.0.0 branch.
