### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Tacuvo** [lightspeeddevelopment/lsx#185]
Hi, 

I am trying to activate TOUR OPERATOR pluggin but is showing me this message:

Warning: require_once(/home/destinos/public_html/wp-content/plugins/tour-operator/includes/shortcodes.php): failed to open stream: No such file or directory in /home/destinos/public_html/wp-content/plugins/tour-operator/tour-operator-bootstrap.php on line 37

I require shortcodes.php, but I dont know how to install it. Can anyone help me?
Thank you.

**Comment by nandotess** [comment]
Hi @Tacuvo, please, can you try again?

You can download the version 1.1.1 [here](https://downloads.wordpress.org/plugin/tour-operator.1.1.1.zip).

Thanks, Fernando
