### ISSUE TITLE
Review the page templates in th theme, test if they are all still needed

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/lsx#19]
Remove any that we dont really use anymore.  or that warrant moving to the child theme

**Comment by krugazul** [comment]
Ive changed the full width narrow to what it actually is,   No Sidebar, a template with no sidebar.

and i removed the page-hero template,  it was exactly the same as page.php

**Comment by rafisegerman** [comment]
Issue resolved, closing.
