### ISSUE TITLE
Always Anchor Regex

### ISSUE THREAD

**Issue by eleshar** [lightspeeddevelopment/lsx#206]
Unanchored regex finds the requested pattern, and leaves room for malicious content.

Without `^` and `$` , the regex searches for any pattern that satisfies the criteria, leaving any unused part of the string available for arbitrary content. 

Reference: https://cwe.mitre.org/data/definitions/625.html

https://github.com/lightspeeddevelopment/lsx/blob/e6fe7304c956a8b5bdbee7ba24c59596d1fadb7d/includes/classes/class-lsx-lazy-load-images.php#L106

https://github.com/lightspeeddevelopment/lsx/blob/e6fe7304c956a8b5bdbee7ba24c59596d1fadb7d/includes/classes/class-lsx-lazy-load-images.php#L112

https://github.com/lightspeeddevelopment/lsx/blob/e6fe7304c956a8b5bdbee7ba24c59596d1fadb7d/includes/classes/class-lsx-lazy-load-images.php#L115

https://github.com/lightspeeddevelopment/lsx/blob/e6fe7304c956a8b5bdbee7ba24c59596d1fadb7d/includes/classes/class-lsx-lazy-load-images.php#L122

https://github.com/lightspeeddevelopment/lsx/blob/e6fe7304c956a8b5bdbee7ba24c59596d1fadb7d/includes/classes/class-lsx-lazy-load-images.php#L125-L126

https://github.com/lightspeeddevelopment/lsx/blob/e6fe7304c956a8b5bdbee7ba24c59596d1fadb7d/includes/classes/class-lsx-nav-walker.php#L38

https://github.com/lightspeeddevelopment/lsx/blob/e6fe7304c956a8b5bdbee7ba24c59596d1fadb7d/includes/extras.php#L448

https://github.com/lightspeeddevelopment/lsx/blob/e6fe7304c956a8b5bdbee7ba24c59596d1fadb7d/includes/template-tags.php#L690

**Comment by krugazul** [comment]
Ive added in the anchor tags
