### ISSUE TITLE
Illegal string offset 'width' and 'height'

### ISSUE THREAD

**Issue by eleshar** [lightspeeddevelopment/lsx#213]
![378 - Luxury Tented Camp Archive_ - https___to-demo lsdev biz_accommodation-type_luxury-tented-camp_](https://user-images.githubusercontent.com/1577675/60939071-a7987b80-a2d6-11e9-9c55-639dd1527cf6.jpg)

**Comment by krugazul** [comment]
@eleshar this error is actually coming from the WP_Media_Image widget, not from the LSX theme.   The stack trace just references LSX.
