### ISSUE TITLE
Related Posts Section uses H1's instead of H2s

### ISSUE THREAD

**Issue by jacquesvdhorst** [lightspeeddevelopment/lsx#217]
While reviewing CTT for Multiple H1, H2 header tags I've noticed the related posts section under a post uses H1's 

Following the requirements:
- One unique H1 per page, post or archive describing what the page is about. This is for most themes the post -, page – or archive title.
- Use H2 through H6 to divide sections of the page, such as widgetized areas, comment sections, etc
- Don’t skip or mix up headings.

We should change the /partials/content.php heading to a h2

**Comment by krugazul** [comment]
@jacquesvdhorst the related posts are located in the LSX Blog Customizer, not the them,  please add the issue there,  and close this one. - https://github.com/lightspeeddevelopment/lsx-blog-customizer
