### ISSUE TITLE
Post Grid Images loading issue.

### ISSUE THREAD

**Issue by joseabreu1985** [lightspeeddevelopment/lsx#229]
There is an issue in the post grid images that prevent the images to load correctly, I have tried various methods to reload the images but nothing happens.

**- Regenerate Thumbnails:** I have tried regenerating the thumbnails but nothing happens, the images for the grids are still missing.

![image_1](https://user-images.githubusercontent.com/20842182/66310905-ada4f500-e8e3-11e9-902b-b142e6bb5468.png)

**- Re-Upload Post images:** I have tried to re-upload manually the images for each post and this work but for three post only the rest of the post still remain without thumbnails in the post grid. This is weird because this images have the same size.

![image_2](https://user-images.githubusercontent.com/20842182/66311093-0bd1d800-e8e4-11e9-9e74-9ead6a1d9860.png)

In the image above I have reloaded the BG and featured images but nothing happens to this post on the grid because still remaining without the featured image. I have tried this method for all the posts existing on this page as I said this method just work for only three posts (see image below)

![image_3](https://user-images.githubusercontent.com/20842182/66311157-358aff00-e8e4-11e9-8824-14386519cb70.png)

**Re-do Post Carousel:** One of the easiest ways to think to resolved this issue was to removed and do a whole new fresh block for the LSX Post Carousel but again nothing real happened with the thumbnails, A weird thing to point out here was the first time I have applied this method I was thinking this actually worked because I did a preview of the changes and the thumbnails were on their positions looking good but I take the link and opened on an incognito window of the browser and thumbnails disappeared again.

![image_4](https://user-images.githubusercontent.com/20842182/66311262-6cf9ab80-e8e4-11e9-8b31-59e288a93142.png)

**- Things to point out:** Looking for what was happening with the thumbnails I have seen a couple of things to point out.

1- As we talked the post carousel in the home doesn’t load the thumbnails but what happens with the “Related Post” carousel inside an actual post? Let’s see the next two images:

![image_5](https://user-images.githubusercontent.com/20842182/66311353-a500ee80-e8e4-11e9-81ab-3c55f86e0809.png)

![image_6](https://user-images.githubusercontent.com/20842182/66311390-b944eb80-e8e4-11e9-8fd6-530d37c0f265.png)

We can easily compare the carousels with one post in common “The Cellars-Hohenort undergoes….” And see in the home carousel that the post doesn’t have the image but in the “related posts” inside the posts the carousel load correctly the thumbnails with a good quality
 
When I have inspected these two carousels I have noticed that they have the same exact structure but in the img tag we can see another structure inside the tag. See images below to compare the img tag structure.
 
Image 1: Home posts carousel.
![image_7](https://user-images.githubusercontent.com/20842182/66311454-e5f90300-e8e4-11e9-8d11-a90e89d02e8b.png)

Image 2: Related posts carousel.
![image_8](https://user-images.githubusercontent.com/20842182/66311515-0628c200-e8e5-11e9-9a56-c9791489141a.png)

I think this may be the cause of the issue because of how the LSX Post Carousel is calling the thumbnails images.

**Comment by krugazul** [comment]
@joseabreu1985 this issue was fixed in the LSX Blocks Plugin via this commit, the [images](https://lsx.lsdev.biz/blocks/post-grid/) generate correctly now. - [https://github.com/lightspeeddevelopment/lsx-blocks/commit/778c7127de3155b3b92c17f79bdd9144c67a6859](https://github.com/lightspeeddevelopment/lsx-blocks/commit/778c7127de3155b3b92c17f79bdd9144c67a6859)
