### ISSUE TITLE
Add a colour swatch to customizer

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/lsx#23]
Integrate a colour swatch for choosing colours

**Comment by ashleyshaw** [comment]
The twenty sixteen theme works really effectively, how much work would it be to implement this screenshot? Please test the colours panel on the twenty sixteen theme. 

![screencapture-lsx-demo-lsdev-biz-wp-admin-customize-php-1465037243572](https://cloud.githubusercontent.com/assets/1805352/15799166/a9475950-2a53-11e6-9440-638fccd4162c.png)
