### ISSUE TITLE
Improved Sensei Template Designs

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx#230]
### Apply new Sensei template designs:
- [x] Courses Overview
- [x] My Course / My Account
- [x] Single Course View / Progress
- [x]  Modules archive
- [x] Single Lesson
- [x] Single Lesson Quiz
- [x] Course participants
- [x] Sensei "My Messages"
- [x] Sensei "Single Message"
- [x] Course Page - with modules and lesson excerpts
- [x] Templates with No permissions messages visible when logged out or have not purchased the course
- [x] Success and error messages
- [x] Side bar and no side bar - show participants, progress lessons an modules in side bar - set up as symbols [Awaiting design]

### Add Improved Styling for all Sensei Extensions:
- [x] Sensei Course Progress
- [x] WooCommerce Paid Courses
- [x] Sensei Certificates - PDF template - based on the certificate builder in sensei
- [x] Sensei Media Attachments
- [x] Sensei Course Participants
- [x] Sensei Share Your Grade
- [x] Sensei Content Drip
- [x] Sensei Media attachments extension 

### Review all Sensei Emails and set base colours:
- [x] learner-completed-course.php
- [x] learner-graded-quiz.php
- [x] new-message-reply.php    
- [x] teacher-completed-course.php    
- [x] teacher-completed-lesson.php    
- [x] teacher-new-course-assignment.php
- [x] teacher-new-message.php
- [x] teacher-quiz-submitted.php
- [x] teacher-started-course.php

**Comment by viscosho** [comment]
These templates have been updated with all the new functionality and styles, and the branchs have been merged, closing
