### ISSUE TITLE
Page content to narrow when on Tablet Resolution

### ISSUE THREAD

**Issue by jacquesvdhorst** [lightspeeddevelopment/lsx#234]
### Issue Description

Experiencing narrow content on tablet view as seen in the screenshot:

![image](https://user-images.githubusercontent.com/35291167/67859104-677a3480-fb23-11e9-9790-327c3a86b9e4.png)
https://verloorjouboep.feedmybeta.com/algemene-vrae/

This seems to be because the `.gutenberg-compatible-template.using-gutenberg .entry-content>div` class is set to 60% max width on this resolution.

**Comment by jacquesvdhorst** [comment]
I've updated this to be `80%` on tablet view

**Comment by krugazul** [comment]
@jacquesvdhorst ive merged in the fix,  and tested it on the VJB site. See screenshot below.

![Screenshot 2019-11-07 at 08 30 21](https://user-images.githubusercontent.com/1805603/68365371-22fd2300-0139-11ea-97dd-8c538dcf68f5.png)
