### ISSUE TITLE
WP 5.3 GB Column block now adds a margin bottom to the block

### ISSUE THREAD

**Issue by jacquesvdhorst** [lightspeeddevelopment/lsx#236]
**Describe the bug**
While testing the new 5.3.RC4 release of WordPress I've noticed they added a `margin-bottom` to their Columns Block This causes spacing between sections that have columns in. Need to remove it in our theme. We can add it ourselves should it be needed.

**To Reproduce**
1. View https://12weekstosleek.feedmybeta.com/
2. Look for 2 different sections

**Expected behaviour**
No set margin for columns so containers with columns in won't cause a gap.

**Screenshots**
Front end view
![image](https://user-images.githubusercontent.com/35291167/68296997-9b62d600-009e-11ea-8b78-1bdd1732d4a7.png)

Inspected view
![image](https://user-images.githubusercontent.com/35291167/68297054-b6354a80-009e-11ea-8e8f-9d8bad101f57.png)

**Desktop**
Present here

**Tablets**
Present here

**Mobile**
Doesn't seem to be an issue on mobile.

**Comment by jacquesvdhorst** [comment]
I've updated LSX theme to remove the extra style.

**Comment by krugazul** [comment]
@jacquesvdhorst   I have merged the `fix/236` branch into the core and closed that pull request #237,   I tested the fix on the 12 Weeks to Sleek site.

![Screenshot 2019-11-14 at 08 38 43](https://user-images.githubusercontent.com/1805603/68833347-ef337780-06bb-11ea-96ec-6f6efd1678bd.png)
