### ISSUE TITLE
Compatibility with Woocommerce Blocks Plugin

### ISSUE THREAD

**Issue by viscosho** [lightspeeddevelopment/lsx#243]
**Describe the bug**
LSX is not compatible with some features of the 'Woocommerce Blocks' plugin.
Specifically the Product Reviews block and Reviews related blocks are giving an js issue if used when LSX is active:

`react-dom.min.js:103 TypeError: Cannot read property 'useSelect' of undefined
    at active-filters-frontend.js:6
    at je (react-dom.min.js:78)
    at ph (react-dom.min.js:215)
    at lh (react-dom.min.js:126)
    at O (react-dom.min.js:121)
    at Sb (react-dom.min.js:213)
    at wh (react-dom.min.js:160)
    at fd (react-dom.min.js:160)
    at react-dom.min.js:163
    at kh (react-dom.min.js:119)`

`wc-blocks-data.js:1 Uncaught TypeError: Cannot read property 'createRegistrySelector' of undefined
    at Module.<anonymous> (wc-blocks-data.js:1)
    at r (wc-blocks-data.js:1)
    at wc-blocks-data.js:1
    at wc-blocks-data.js:1`

`data-controls.min.js:1 Uncaught TypeError: Cannot read property 'createRegistryControl' of undefined
    at Module.317 (data-controls.min.js:1)
    at r (data-controls.min.js:1)
    at wp.dataControls.17 (data-controls.min.js:1)
    at data-controls.min.js:1`

`data.min.js:1 Uncaught TypeError: Cannot read property 'flowRight' of undefined
    at Module.348 (data.min.js:1)
    at r (data.min.js:1)
    at wp.data.0 (data.min.js:1)
    at data.min.js:1`

`gutenberg.feedmybeta.com/:1681 Uncaught ReferenceError: wp is not defined
    at (index):1681
    at (index):1682`

**To Reproduce**
- Install and Active LSX theme
- Install and activate Woocommerce
- Create some products and add reviews for them
- Install the [Woocommerce Blocks plugin](https://wordpress.org/plugins/woo-gutenberg-products-block/)
- Create a new page and call the reviews block.
- Save and see the page on front

**Expected behaviour**
The block should display all Reviews or a specific product review, according to the block config.

Screenshots
This is the revies block on the backend admin page, working ok
<img width="1208" alt="Screen Shot 2019-12-03 at 5 02 53 PM" src="https://user-images.githubusercontent.com/3129483/70085418-ee24a480-15ee-11ea-88b7-441368d89af5.png">

This is the revies block on the front page, showing and empty div and js errors
<img width="1321" alt="Screen Shot 2019-12-03 at 5 03 30 PM" src="https://user-images.githubusercontent.com/3129483/70085444-009ede00-15ef-11ea-8458-e2b2f5e5b58c.png">

Desktop:
Happening in all browsers.

Mobile:
Happening in device.

**Comment by krugazul** [comment]
@viscosho I have tested this bug on the [LSX site](https://lsx.lsdev.biz/third-party-plugins/woocommerce-blocks/), it looks like the error has been resolved.  Im not seeing any error in the console, and the review is displaying.  This could have been reloved due to an update with the WooCommerce Blocks plugin.  I have updated to 2.5.10 the latest, and all blocks are displaying fine.   The reviews block does need some styling,  i will create an issue for that.

![Screenshot 2020-01-11 at 11 25 27](https://user-images.githubusercontent.com/1805603/72202290-3644ab80-3466-11ea-8e86-476041e44175.png)
