### ISSUE TITLE
Dropdown menu for a portait ipad

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/lsx#25]
Whatever menu system we are using (bootstrap walker) or (wp nav walker)  is making the li encasing a submenu a drop down trigger.

Now we have added styles to force the dropdown to show,  so the dropdown toggle is still there.

We need to either remove the dropdown toggle class, or add in the hack i made.

**Comment by ashleyshaw** [comment]
Is this still an issue?
