### ISSUE TITLE
This is not vertically centered

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx#250]
**Describe the bug**
Banner title is not vertically centered on team archive pages or other archive pages.

**To Reproduce**
You can see it on any page that has an archive banner: https://lsx-demo.lsdev.biz/testimonials/

**Expected behaviour**
Centered text vertically and horizontally.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/3129483/70564124-56830100-1b6e-11ea-9288-cc59f52e2cf1.jpg)

**Desktop:**
Happening in all browsers.

**Mobile:**
Happening in device.

**Reference**
[https://www.bugherd.com/projects/97685/tasks/397](https://www.bugherd.com/projects/97685/tasks/397)

**Comment by viscosho** [comment]
This was fixed on this branch: https://github.com/lightspeeddevelopment/lsx/pull/292

**Comment by ashleyshaw** [comment]
This was fixed on this branch: https://github.com/lightspeeddevelopment/lsx/pull/292
