### ISSUE TITLE
Banner image is not pulling through the feature image

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx#252]
[https://www.bugherd.com/projects/97685/tasks/399](https://www.bugherd.com/projects/97685/tasks/399)

**Comment by viscosho** [comment]
This is working as expected now, the image needs to be edited in each taxonomy option: https://lsx-demo.lsdev.biz/wp-admin/term.php?taxonomy=project-group&tag_ID=182&post_type=project
