### ISSUE TITLE
Here is the design - https://projects.invisionapp.com/d/main#/console/3888030/264361988/preview

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx#253]
Update my account page login to match the design. 
Here is the design -
[https://projects.invisionapp.com/d/main#/console/3888030/264361988/preview](https://projects.invisionapp.com/d/main#/console/3888030/264361988/preview)

- [x] Update breadcrumb if its WC page
- [x] Update button colors
- [x] Update link colors
- [x] Test social login

**Reference**
[https://www.bugherd.com/projects/97685/tasks/371](https://www.bugherd.com/projects/97685/tasks/371)

**Comment by viscosho** [comment]
This was fixed on this branch: https://github.com/lightspeeddevelopment/lsx/pull/292

**Comment by ashleyshaw** [comment]
This was fixed on this branch: https://github.com/lightspeeddevelopment/lsx/pull/292
