### ISSUE TITLE
We need to fix the padding on this message if no learners are taking the course

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx#254]
**Describe the bug**
We need to fix the padding on this message if no learners are taking the course.

**To Reproduce**
Check any course that has no learners, specifically a single lesson: https://lsx-demo.lsdev.biz/lesson/advanced-lsx/

**Expected behaviour**
Needs more padding and text formatting.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/3129483/70565058-14f35580-1b70-11ea-94cc-7669b1e7e12c.jpg)

**Desktop:**
Happening in all browsers.

**Mobile:**
Happening in device.

**Reference**
[https://www.bugherd.com/projects/97685/tasks/382](https://www.bugherd.com/projects/97685/tasks/382)

**Comment by ashleyshaw** [comment]
This has been updated on core LXS

**Comment by viscosho** [comment]
This has been fixed and is part of this pull request: https://github.com/lightspeeddevelopment/lsx/pull/284
