### ISSUE TITLE
I am sure there is a line spacer between the tabs

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx#255]
To do:

- [x] Add a line spacer between the tabs in the Learner Profile
- [x] Test on mobile
- [x] Fix the button above the menu

**Screenshot of how it looks now:**
<img width="470" alt="Screen Shot 2019-12-10 at 5 16 38 PM" src="https://user-images.githubusercontent.com/3129483/70565450-ea55cc80-1b70-11ea-9457-7a0236e7987e.png">

**How it should look:**
<img width="378" alt="Screen Shot 2019-12-10 at 5 18 01 PM" src="https://user-images.githubusercontent.com/3129483/70565521-140ef380-1b71-11ea-85c1-b7a34453d5de.png">

**Reference**
[https://www.bugherd.com/projects/97685/tasks/395](https://www.bugherd.com/projects/97685/tasks/395)

**Comment by ashleyshaw** [comment]
This has been updated on core LXS

**Comment by viscosho** [comment]
This has been fixed and is part of this pull request: https://github.com/lightspeeddevelopment/lsx/pull/284
