### ISSUE TITLE
please have a look at the design again for the ratio between image and content. Design shows the image at 380 px width and the content has a width 685px with in the card.

this doesnt have to be exactly as above sizes but ideally i'd like to get it a bit closer to design - https://share.goabstract.com/e21a06ae-eddb-4e21-b868-2d2d8353539f?mode=build&sha=265fe04b1c103b6a5f8e6459d2509808fd01b115

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx#256]
**To do:**

Please have a look at the design again for the ratio between image and content. Design shows the image at 380 px width and the content has a width 685px with in the card.this doesnt have to be exactly as above sizes but ideally i'd like to get it a bit closer to design - https://share.goabstract.com/e21a06ae-eddb-4e21-b868-2d2d8353539f?mode=build&sha=265fe04b1c103b6a5f8e6459d2509808fd01b115

**How to Reproduce**
You can see the courses archive pages https://lsx-demo.lsdev.biz/courses-overview/

**Expected behaviour**
<img width="665" alt="Screen Shot 2019-12-10 at 5 21 07 PM" src="https://user-images.githubusercontent.com/3129483/70565739-7962e480-1b71-11ea-990e-096207cb2797.png">

**Reference**
[https://www.bugherd.com/projects/97685/tasks/384](https://www.bugherd.com/projects/97685/tasks/384)

**Comment by ashleyshaw** [comment]
I'm trying to make this style as general because the plugin has sizing options for thumbnails, so I'm respecting that

**Comment by viscosho** [comment]
This has been fixed and is part of this pull request: https://github.com/lightspeeddevelopment/lsx/pull/284
