### ISSUE TITLE
Why is this here?

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx#258]
**Describe the bug**
There is a 'Comments are closed' message showing on single events or single lessons. It should have comments open or not show anything.

**To Reproduce**
Check any single event like: https://lsx-demo.lsdev.biz/event/womens-health-secret-sweats/

**Expected behaviour**
It should have comments open or not show anything.It should have comments open or not show anything.

**Screenshots**
![screenshot (2)](https://user-images.githubusercontent.com/3129483/70566372-b8456a00-1b72-11ea-901a-929f897cedf8.jpg)

**Reference**
[https://www.bugherd.com/projects/97685/tasks/364](https://www.bugherd.com/projects/97685/tasks/364)

**Comment by viscosho** [comment]
This is a plugin configuration, there is a general option on the Tribe Events plugin options, that allows you to enable or disable all comments on events, also, if they are enabled, each single event has the option to open or close comments individually:

General setting:
<img width="538" alt="Screen Shot 2020-03-12 at 9 19 46 AM" src="https://user-images.githubusercontent.com/3129483/76521005-be353a80-6442-11ea-9cf2-26e5c0a32c05.png">

Individual event setting:
<img width="558" alt="Screen Shot 2020-03-12 at 9 07 54 AM" src="https://user-images.githubusercontent.com/3129483/76521013-bffefe00-6442-11ea-8bad-2bea5143bed7.png">
