### ISSUE TITLE
This doesnt look right. I think we need to left align the message box and send message button and increase the width of the message box. Jacques did a design for this here - https://share.goabstract.com/e73586d2-c57e-4270-b351-48ca8a88390e?mode=design&sha=265fe04b1c103b6a5f8e6459d2509808fd01b115

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx#262]
**Describe the issue**
This doesn't look right. I think we need to left align the message box and send message button and increase the width of the message box. 
Jacques did a design for this here - https://share.goabstract.com/e73586d2-c57e-4270-b351-48ca8a88390e?mode=design&sha=265fe04b1c103b6a5f8e6459d2509808fd01b115

**Screenshot**
![screenshot](https://user-images.githubusercontent.com/3129483/70624579-541cb780-1bff-11ea-9584-a770aab79aba.jpg)

**Reference**
[https://www.bugherd.com/projects/97685/tasks/387](https://www.bugherd.com/projects/97685/tasks/387)

**Comment by ashleyshaw** [comment]
Fixed on lsx core

**Comment by viscosho** [comment]
This has been fixed and is part of this pull request: https://github.com/lightspeeddevelopment/lsx/pull/284
