### ISSUE TITLE
This title is not working, the archive page title is not being called from the options

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx#267]
**Describe Issue**
The Banner image and title for the Events archive page is not working.

**To Reproduce**
- Go to the event archive page
- Notice if it has a banner
- Go to the backend to theme options
- Try adding new banner image or title to the event archive page.

**Screenshot**
![screenshot](https://user-images.githubusercontent.com/3129483/70660470-0759d080-1c41-11ea-8898-faf50f81b899.jpg)

**Reference**
[https://www.bugherd.com/projects/97685/tasks/362](https://www.bugherd.com/projects/97685/tasks/362)

**Comment by krugazul** [comment]
The custom title from the theme options has been fixed.  It is now pulling through to the events archive page.

![Screenshot 2020-03-18 at 06 36 00](https://user-images.githubusercontent.com/1805603/76925963-cd553600-68e3-11ea-8b28-eb85fb1666d8.png)
