### ISSUE TITLE
image overlaps container

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx#270]
**Describe the Issue**
The course image overlaps the container on Learners profile page

**To Reproduce**
- Go to any learner profile that has taken an course and that course has a big featured image.

**Screenshot**
![screenshot](https://user-images.githubusercontent.com/3129483/70633396-45d69780-1c0f-11ea-868c-f81c223f39f4.jpg)

**Reference**
[https://www.bugherd.com/projects/97685/tasks/393](https://www.bugherd.com/projects/97685/tasks/393)

**Comment by ashleyshaw** [comment]
This was fixed on core LSX

**Comment by viscosho** [comment]
This has been fixed and is part of this pull request: https://github.com/lightspeeddevelopment/lsx/pull/284
