### ISSUE TITLE
no spacing between items

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx#271]
**Describe Issue**
There is no spacing between items on the My Course archive page.

**To Reproduce**
- Go to a page that has the my course archive shortcode

**Screenshot**
![screenshot](https://user-images.githubusercontent.com/3129483/70656939-c4e0c580-1c39-11ea-96c6-128435ead858.jpg)

**Reference**
[https://www.bugherd.com/projects/97685/tasks/392](https://www.bugherd.com/projects/97685/tasks/392)

**Comment by ashleyshaw** [comment]
Fixed on Core LSX

**Comment by viscosho** [comment]
This has been fixed and is part of this pull request: https://github.com/lightspeeddevelopment/lsx/pull/284
