### ISSUE TITLE
no gap between selectors

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx#272]
**Describe the Issue**
No gap between Tabs in Learners profile page

To Reproduce
- Go to any Learners profile page that has taken a course
- Take a look at the tab menu below the learner description.

**Screenshot**
![screenshot](https://user-images.githubusercontent.com/3129483/70633756-ca291a80-1c0f-11ea-938e-ac44da27e53e.jpg)

**Reference**
[https://www.bugherd.com/projects/97685/tasks/391](https://www.bugherd.com/projects/97685/tasks/391)

**Comment by ashleyshaw** [comment]
This has been updated on core LXS

**Comment by viscosho** [comment]
This has been fixed and is part of this pull request: https://github.com/lightspeeddevelopment/lsx/pull/284
