### ISSUE TITLE
on this page the text size in the button looks correct, but there are multiple instances on other pages where the button text is quite a bit smaller than this, please check and make sure this is consistent 

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx#273]
**To DO**
- [x] Test all buttons in all Sensei templates and make sure they have the right size, styling and color.

**Screenshot**
![screenshot](https://user-images.githubusercontent.com/3129483/70657221-2a34b680-1c3a-11ea-9252-3b230efb1b22.jpg)

**Reference**
[https://www.bugherd.com/projects/97685/tasks/390](https://www.bugherd.com/projects/97685/tasks/390)

**Comment by ashleyshaw** [comment]
Updated all the buttons I could find on core LSX

**Comment by viscosho** [comment]
This has been fixed and is part of this pull request: https://github.com/lightspeeddevelopment/lsx/pull/284
