### ISSUE TITLE
this spacing goes weird when the contact teacher message box is open

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx#274]
**Describe Bug**
There is a weird when the contact teacher message box is open, on the single course page.

**To Reproduce**
- Go to a single course page
- Click the 'Contact Teacher' button
- See the spacing changes.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/3129483/70655996-fe183600-1c37-11ea-9cd2-cc3a7e35ec17.jpg)

**Reference**
[https://www.bugherd.com/projects/97685/tasks/388](https://www.bugherd.com/projects/97685/tasks/388)

**Comment by ashleyshaw** [comment]
This was fixed in LSX core

**Comment by viscosho** [comment]
This has been fixed and is part of this pull request: https://github.com/lightspeeddevelopment/lsx/pull/284
