### ISSUE TITLE
the button text looks a little small here... is this correct?

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx#275]
**Describe Issue**
The button Next Lesson text looks a little small in the button of the single lesson.

**To Reproduce**
- Go to a single lesson and see button

**Screenshot**
![screenshot](https://user-images.githubusercontent.com/3129483/70656160-4c2d3980-1c38-11ea-9053-e87878722394.jpg)

**Reference**
[https://www.bugherd.com/projects/97685/tasks/386](https://www.bugherd.com/projects/97685/tasks/386)

**Comment by ashleyshaw** [comment]
Fixed on LSX core

**Comment by viscosho** [comment]
This has been fixed and is part of this pull request: https://github.com/lightspeeddevelopment/lsx/pull/284
