### ISSUE TITLE
these buttons should be aligned at the top

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx#276]
**Describe Issue**
The 'Contact Lesson' buttons should be aligned at the top on a single lesson page.

**To Reproduce**
- Go to a single lesson and check the button

**Screenshot**
![screenshot](https://user-images.githubusercontent.com/3129483/70656479-ebeac780-1c38-11ea-8b0e-26ceabce7f4a.jpg)

**Reference**
[https://www.bugherd.com/projects/97685/tasks/385](https://www.bugherd.com/projects/97685/tasks/385)

**Comment by ashleyshaw** [comment]
Fixed on LSX core

**Comment by viscosho** [comment]
This has been fixed and is part of this pull request: https://github.com/lightspeeddevelopment/lsx/pull/284
