### ISSUE TITLE
Change to "Messages" because it links to all messages

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx#277]
**To Do**
- [x] Change to "Messages" the breadcrumbs on a single messages page.

**Screenshot** 
![screenshot](https://user-images.githubusercontent.com/3129483/70656666-4552f680-1c39-11ea-962b-7b43a48d21a4.jpg)

**Reference**
[https://www.bugherd.com/projects/97685/tasks/380](https://www.bugherd.com/projects/97685/tasks/380)

**Comment by ashleyshaw** [comment]
Fixed on core LSX

**Comment by viscosho** [comment]
This has been fixed and is part of this pull request: https://github.com/lightspeeddevelopment/lsx/pull/284
