### ISSUE TITLE
I am pretty sure there needs to be some spacer or something between the tabs, see other tabs - https://lsx-demo.lsdev.biz/courses-overview/



### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx#278]
[https://www.bugherd.com/projects/97685/tasks/378](https://www.bugherd.com/projects/97685/tasks/378)

**Comment by viscosho** [comment]
This is a duplicate for this one: https://github.com/lightspeeddevelopment/lsx/issues/255

**Comment by ashleyshaw** [comment]
Duplicated
