### ISSUE TITLE
Can we label this as "Events" instead of "Tribe_events"

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx#279]
**To Do**
- [x] Can we label this as "Events" instead of "Tribe_events" 

**Screenshot**
![screenshot](https://user-images.githubusercontent.com/3129483/70822831-42810e80-1dbd-11ea-8e0a-758ae9b9af53.jpg)

**Reference**
[https://www.bugherd.com/projects/97685/tasks/242](https://www.bugherd.com/projects/97685/tasks/242)

**Comment by ashleyshaw** [comment]
This was fixed on lsx search core

**Comment by viscosho** [comment]
This was fixed on lsx search core, see commit: https://github.com/lightspeeddevelopment/lsx-search/commit/a641e225ac864c5104c6eb6969a90f96c1949e7b
