### ISSUE TITLE
Spacing doesn't seem correct here, is there any design guidance you can follow?

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx#281]
**Describe Issue**
The Spacing of the price does not seem right. add more spacing

**To Reproduce**
- Go to a single course that is a paid course.

**Screenshot**
![screenshot](https://user-images.githubusercontent.com/3129483/70656782-821eed80-1c39-11ea-911f-51ce84c09165.jpg)

**Reference**
[https://www.bugherd.com/projects/97685/tasks/370](https://www.bugherd.com/projects/97685/tasks/370)

**Comment by ashleyshaw** [comment]
Fixed on core LSX

**Comment by viscosho** [comment]
This has been fixed and is part of this pull request: https://github.com/lightspeeddevelopment/lsx/pull/284
