### ISSUE TITLE
If there is not thumbnail the spacing should be even too

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx#287]
[https://www.bugherd.com/projects/97685/tasks/400](https://www.bugherd.com/projects/97685/tasks/400)

**Comment by ashleyshaw** [comment]
Fixed on core blog customizer

**Comment by viscosho** [comment]
Fixed here: https://github.com/lightspeeddevelopment/lsx-blog-customizer/commit/0e597b3ac7b3e2666df42f51543e2866e9d64fa9
