### ISSUE TITLE
Spacing at the bottom should be even

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx#288]
[https://www.bugherd.com/projects/97685/tasks/401](https://www.bugherd.com/projects/97685/tasks/401)

**Comment by ashleyshaw** [comment]
Fixed on core search plugin

**Comment by viscosho** [comment]
Fixed here: https://github.com/lightspeeddevelopment/lsx-search/commit/108acb566e980c01140b829f1b5cff9b66f75212
