### ISSUE TITLE
Breadcrumbs aren't displaying properly. 

### ISSUE THREAD

**Issue by antonvandiermen** [lightspeeddevelopment/lsx#29]
Issue is visible on this page https://www.lsdev.biz/portfolio/mushara-collection-website/

![screen shot 2015-09-02 at 2 32 24 pm](https://cloud.githubusercontent.com/assets/14092353/9631602/623ba426-5182-11e5-8c98-15c5c1290397.png)

**Comment by ashleyshaw** [comment]
No longer relevant.
