### ISSUE TITLE
Is this the correct spacing?

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx#297]
[https://www.bugherd.com/projects/97685/tasks/404](https://www.bugherd.com/projects/97685/tasks/404)

**Comment by ashleyshaw** [comment]
Fixed on blog customizer core

**Comment by viscosho** [comment]
Fixed on this commit https://github.com/lightspeeddevelopment/lsx/commit/3a780f6d002aac132d0276f76606f7eba6ef5ed9

**Comment by ashleyshaw** [comment]
Spacing has been checked,  it has been reduced.
