### ISSUE TITLE
Fix this one button, is not well aligned

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx#299]
[https://www.bugherd.com/projects/97685/tasks/406](https://www.bugherd.com/projects/97685/tasks/406)

**Comment by ashleyshaw** [comment]
Fixed on lsx core

**Comment by viscosho** [comment]
Fixed on this commit https://github.com/lightspeeddevelopment/lsx/commit/3a780f6d002aac132d0276f76606f7eba6ef5ed9

**Comment by ashleyshaw** [comment]
This button has been styled as well.
