### ISSUE TITLE
Fix this button, is not aligned correctly

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx#300]
[https://www.bugherd.com/projects/97685/tasks/407](https://www.bugherd.com/projects/97685/tasks/407)

**Comment by ashleyshaw** [comment]
Fixed on lsx core

**Comment by viscosho** [comment]
Fixed in this commit: https://github.com/lightspeeddevelopment/lsx/commit/3a780f6d002aac132d0276f76606f7eba6ef5ed9

**Comment by ashleyshaw** [comment]
Button has button aligned and styled according to the design.
