### ISSUE TITLE
Theme Sniffer Errors for 2.6.2

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/lsx#302]
**Goal**
@viscosho there are 286 errors left on the theme sniffer,  we should aim to do 143 this round.  It sounds like a lot, but most of them are quick fixes. We will update off the list on #295 for LSX 2.7

**To Reproduce**
1. Install the Theme Sniffer plugin
2. Go to the plugin settings
3. Run a review for LSX

**Expected behavior**
The bug should not appear in the list any more.

**Comment by viscosho** [comment]
@krugazul  I merged the first theme sniffer branch with master and created a second branch with all the latest: https://github.com/lightspeeddevelopment/lsx/tree/fix-302-theme-sniffer
Working on this branch now.

**Comment by krugazul** [comment]
@viscosho I did a theme sniffer check,  we are down to 201 bugs :-)

**Comment by viscosho** [comment]
@krugazul  I added another updated branch to continue with this: https://github.com/lightspeeddevelopment/lsx/tree/fix/302

**Comment by viscosho** [comment]
I added a final batch of fixes in this pr: https://github.com/lightspeeddevelopment/lsx/pull/337
