### ISSUE TITLE
Add styling for captions on  WP core image and video blocks

### ISSUE THREAD

**Issue by viscosho** [lightspeeddevelopment/lsx#304]
**To Do.**
Add styling for captions on  WP core image and video blocks

**Images**
Caption
<img width="887" alt="Screen Shot 2020-01-10 at 4 02 57 PM" src="https://user-images.githubusercontent.com/3129483/72178912-b74a6700-33c2-11ea-9e08-d2a44bc1b00c.png">

Video
<img width="923" alt="Screen Shot 2020-01-10 at 4 02 52 PM" src="https://user-images.githubusercontent.com/3129483/72178918-bb768480-33c2-11ea-8524-eee5f25e6d6f.png">

**Design**
https://projects.invisionapp.com/d/main#/console/19153622/399997514/preview

**Comment by viscosho** [comment]
Added new styles on this branch: https://github.com/lightspeeddevelopment/lsx/tree/enhace-304-captions

**Comment by jacquesvdhorst** [comment]
@viscosho - I've pulled this branch onto https://gutenberg.feedmybeta.com/ and tested on https://gutenberg.feedmybeta.com/2019/10/23/artisan-themes-sample-gutenberg-block-content/

There seems to be a small gap between the caption and item on the Embedded Items:

![image](https://user-images.githubusercontent.com/35291167/72237756-44b8d180-35e4-11ea-89ee-76fa59f88b59.png)

**Comment by viscosho** [comment]
@jacquesvdhorst  that spacing issue was fixed on the branch, please test and if you are happy merge the PR: https://github.com/lightspeeddevelopment/lsx/pull/305
