### ISSUE TITLE
Add styling for the WooCommerce Reviews Block

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/lsx#306]
**WooCommerce Reviews Block Integration**
The WooCommerce Reviews block integration has been fixed, and now requires styling to bring it inline with the LSX Theme styling.

[Example Page](https://lsx.lsdev.biz/third-party-plugins/woocommerce-blocks/)

![Screenshot 2020-01-14 at 10 05 34](https://user-images.githubusercontent.com/1805603/72325282-6fbf2600-36b5-11ea-953c-f115d071eaf7.png)

**Comment by deonschreiber** [comment]
@krugazul This has been updated on the style guide:
https://projects.invisionapp.com/d/main#/console/19153622/400809035/preview

### Design Screenshot
![wc-reviews-block](https://user-images.githubusercontent.com/31090573/72435845-ba20cf80-37a7-11ea-875e-28791e96509e.png)

Styling required on the Order by drop down
**Styling requirement
![Screenshot 2020-01-15 at 14 58 56](https://user-images.githubusercontent.com/31090573/72435898-dcb2e880-37a7-11ea-9f0c-250470f20736.png)
**

**Comment by viscosho** [comment]
@jacquesvdhorst  please review this, I have created a branch and a PR to improve these styles: https://github.com/lightspeeddevelopment/lsx/pull/314
