### ISSUE TITLE
The new WooCommerce Blocks need styling integration 

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/lsx#307]
**Problem**
WooCommerce has added 2 new blocks to their list.

**Solution**
We need to please add styling following the LSX format for these items.

- [x] [WC All Products](https://gutenberg.feedmybeta.com/wc-blocks-test/)
- [x] [WC Filters blocks](https://gutenberg.feedmybeta.com/wc-blocks-test/)

**Resources**
 - Here is an example of the [shop page](https://lsx-demo.lsdev.biz/shop/) with filters that you can possibly reuse the styling.
 - Invision Design - https://projects.invisionapp.com/d/main#/console/19153622/400809035/comments

![Screenshot 2020-01-17 at 12 32 20](https://user-images.githubusercontent.com/1805603/72605668-e2ced380-3925-11ea-975e-f7a3a0658a6d.png)

**Comment by viscosho** [comment]
@krugazul  I have finish this and created a PR: https://github.com/lightspeeddevelopment/lsx/pull/313

**Notes:**

Styles added for compatibility out of the box
A special class lsx-wc-filter-block was created on the css to add to a block container, this class will give spacing to a 2 column block inside of it with the filter blocks on the left and the all products grid on the right (the most common layout)
