### ISSUE TITLE
WP Popup Maker Integration with our 4 main pop ups

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/lsx#308]
**Problem**
We keep adding styles for the pop ups to the child themes.  And we end up doing so over and over.

**Solution**
Lets reuse our code and add an integration to the LSX theme. So when we activate the plugin and add the templates, they work.

**To Do**
 - [x] Create a new SCSS module to handle the styles.
 - [x] Rectangular Pop Up
 - [x] Square Sign up without image
 - [x] Mini Square Sign up with image

![Screenshot 2020-01-17 at 16 40 19](https://user-images.githubusercontent.com/1805603/72620551-318d6500-3948-11ea-8b1c-34da2fc801ee.png)

![Screenshot 2020-01-17 at 16 40 26](https://user-images.githubusercontent.com/1805603/72620702-7c0ee180-3948-11ea-83c1-ee12d2d99e66.png)

![Screenshot 2020-01-17 at 16 40 33](https://user-images.githubusercontent.com/1805603/72620561-34885580-3948-11ea-8840-2c0ccfad7717.png)

**Comment by viscosho** [comment]
@deonschreiber  please test (in an incognito window)
Rectangular Pop Up: https://lsx-demo.lsdev.biz/
Square Sign up with image: https://lsx-demo.lsdev.biz/shop/
Mini Square Sign up with image: https://lsx-demo.lsdev.biz/contact/

This is the branch where I worked: https://github.com/lightspeeddevelopment/lsx/tree/add/308

And this is the pull request: https://github.com/lightspeeddevelopment/lsx/pull/310
