### ISSUE TITLE
The API options are not showing when certain plugins are on, like lsx-banners 

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx#309]
**The Issue**
The API options are not showing when certain plugins are on, like lsx-banners

**To Reproduce**
- Install LSX and LSX Customizer
- Install another LSX like LSX Blocks or one of the usual LSX plugins
- Install LSX Banners
- Go to Appearance -> theme options
- Go to the PAI tab
- See error

**Error**:
![screenshot](https://user-images.githubusercontent.com/3129483/74077570-77959000-49ff-11ea-85cd-49fb1aaa5bf3.jpg)

**Reference**
[https://www.bugherd.com/projects/97685/tasks/409](https://www.bugherd.com/projects/97685/tasks/409)

**Comment by krugazul** [comment]
Im closing this task,  the code was removed from all of the LSX repos, except the LSX Currencies. - [https://www.bugherd.com/projects/200483/tasks/49](https://www.bugherd.com/projects/200483/tasks/49)
