### ISSUE TITLE
WPform Checkboxes mobile style needs to improve

### ISSUE THREAD

**Issue by joseabreu1985** [lightspeeddevelopment/lsx#317]
**Describe the bug**
The forms checkboxes are not displaying correctly on mobile and tablet devices, The checkbox are bigger than the text and the text have incorrect positions.

**To Reproduce**
1. Make sure you have installed the WPforms plugin
2. Create a new form with checkboxes fields
3. Test the form on a phone or tablet device or use a browser inspector or Browserstack on mobile formats
4. See error.

**Expected behavior**
The checkboxes should have a better responsive size for any smaller device and the text should be aligned in the same line with the boxes.

**Screenshots**
Checkboxes on Mobile devices with the wrong style.
<img width="288" alt="checkbox-fields-mobile" src="https://user-images.githubusercontent.com/20842182/74336861-e7987300-4d7d-11ea-9806-243499b9df06.png">

Checkboxes on desktop with the correct style.
<img width="715" alt="checkbox-fields-desktop" src="https://user-images.githubusercontent.com/20842182/74336893-faab4300-4d7d-11ea-8847-78bf44685239.png">

**Desktop (please complete the following information):**
 - OS: Not applicable
 - Browser: Not applicable
 - Version: Not applicable.

**Smartphone (please complete the following information):**
 - Device: Happen on all devices.
 - OS: Happen on all OS.
 - Browser: Happen on all Browsers.
 - Version: Happen on all versions.

Additional context
I have tested the form and the issue comes from a padding that increase the size of the boxes on smaller devices.

**Comment by viscosho** [comment]
@joseabreu1985  please see the Pull request: https://github.com/lightspeeddevelopment/lsx/tree/fix/317
which has the fixes for this issue
