### ISSUE TITLE
"Older Posts" button overlaps slightly with the footer area.

### ISSUE THREAD

**Issue by antonvandiermen** [lightspeeddevelopment/lsx#32]
![lightspeed-blog](https://cloud.githubusercontent.com/assets/14092353/9735215/78878d42-5639-11e5-81f3-abd638fd00ee.png)

LSDev.biz should be using wp-pagenavi, not infinite scroll. When using infinite scroll in LSX though, the older post overlap styling issue occurs, which needs to be fixed in LSX.

https://app.asana.com/0/35490707359542/47915966397572

**Comment by ashleyshaw** [comment]
Old task, no longer relevant
