### ISSUE TITLE
@Virginia I see the white isn't reaching the end here.

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx#320]
[https://www.bugherd.com/projects/97685/tasks/412](https://www.bugherd.com/projects/97685/tasks/412)

**Comment by viscosho** [comment]
This has been fixed on the LSX core:, on this commit: https://github.com/lightspeeddevelopment/lsx/commit/8582535202a69b3cd318f312573433f9d5547013
