### ISSUE TITLE
Expanded Filters on Mobile is showing some text breaking out under the selections.

Couldn't get a mobile view report but you will see once you change the screen

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx#322]
[https://www.bugherd.com/projects/97685/tasks/414](https://www.bugherd.com/projects/97685/tasks/414)

**Comment by viscosho** [comment]
This has been fixed on the LSX core:, on this commit: https://github.com/lightspeeddevelopment/lsx/commit/8582535202a69b3cd318f312573433f9d5547013
