### ISSUE TITLE
New mobile menu theme option

### ISSUE THREAD

**Issue by deonschreiber** [lightspeeddevelopment/lsx#326]
**Improvements to mobile menu UI and visual layout**
In some instances the mobile and tablet menu views are to linear and divided by the main navigation elements, namely: top bar, logo, menu bar and breadcrumbs. All these elements normally have a different background colour so the over all visual effect can appear cluttered, linear and banded.

**Solution**
Create a theme option in the customizer, for the new hamburger style mobile and tablet menu. See attached screenshots, as well as Style Guide link on abstract 

**Alternatives**
We could replace the existing menu entirely with the new layout. However there are still benefits to the old layout, so best to have a theme option whereby we can select either layout.

**Screenshot**

![screenshot-mobile-menu-enhancement](https://user-images.githubusercontent.com/31090573/74712928-2b80f180-5230-11ea-9810-0ff01fa24ce8.png)

**Abstract**
https://share.goabstract.com/d57d6a0f-37bf-4c9c-a18f-29a8de986965?mode=design&sha=2f3117a09a6da9e09f83684b966fc91c75e7fd7d

**Comment by krugazul** [comment]
@viscosho creating the control will be easy enough,  it is just the following 2 files.   You would need to make sure to add `_mobile_` before like `LSX_Customize_Mobile_Header_Layout_Control`

- [https://github.com/lightspeeddevelopment/lsx/blob/master/assets/js/admin/customizer-header-layout.js](https://github.com/lightspeeddevelopment/lsx/blob/master/assets/js/admin/customizer-header-layout.js)
- [https://github.com/lightspeeddevelopment/lsx/blob/master/includes/classes/class-lsx-customize-header-layout-control.php](https://github.com/lightspeeddevelopment/lsx/blob/master/includes/classes/class-lsx-customize-header-layout-control.php)

You will need to check what the CSS entails,  look at what CSS class it uses, and you will need to extend that for the mobile.

**Comment by viscosho** [comment]
Pull request with this improvements: https://github.com/lightspeeddevelopment/lsx/pull/327
