### ISSUE TITLE
Update Title settings in Block Editor "Document Settings" sidebar for static pages

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx#361]
### Document Settings Section to static pages called "Page Title"

- Disable title = used when a cover block is more applicable, when disabled do we grey out the options
- Style Types = Simple Title (Default)
- Text Fields Options
  - Title text
  - Sub title text 
- Title Alignment Options
  - Left
  - Centre
  - Right
- Colours
  - Text colour
  - Background colour

**Comment by krugazul** [comment]
This issue is no longer relevant,  We have reduced the default title to its basic forms,  any customization will be done via a block.
