### ISSUE TITLE
Add styling support for the Yoast SEO plugin HowTo block

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx#363]
### Is your enhancement related to a problem? Please describe.
LSX already supports Yoast SEO breadcrumbs (which includes structured data). We need to continue to add support to LSX for various new Yoast SEO features and blocks. 

The Yoast HowTo block allows adding a set of questions and corresponding answers to a post or page. This is based on Schema.org's 'Question' format, so search engines actually understand that your post or page addresses a question, as posed by a user. And in the future, Google will show your post or page as such in its search results.

The Yoast SEO block does not look very good when used with the LSX theme. 

### Describe the solution you'd like
Add styling support for the Yoast FAQ block to the LSX Theme using this [developer documentation](https://developer.yoast.com/blog/theming-gutenberg-the-faq-block/).

Consider using existing [Bootstrap Collapse JavaScript](https://getbootstrap.com/docs/3.3/javascript/#collapse) component and LSX styling classes. 

### Design: FAQ with clear visual separation

![FAQ-design-suggestion](https://user-images.githubusercontent.com/1805352/83270929-70baa500-a1c9-11ea-88ee-41706d492c3a.jpg)

### Design: FAQ with collapsible headers

![FAQ-collapsableheader](https://user-images.githubusercontent.com/1805352/83270940-7617ef80-a1c9-11ea-8b60-b3a56580500a.jpg)

### Describe alternatives you've considered
We could use the LSX Blocks Accordion block, but that does not include the structured data support that Yoast SEO does. Considering we install Yoast SEO on all our sites we might as well use their blocks. 

### Additional context
The FAQ Block will only be used on FAQ pages, [read more](https://yoast.com/how-to-build-an-faq-page/) how we can use Yoast SEO to build a structured data-powered FAQ page using Yoast SEO

**Comment by jacquesvdhorst** [comment]
LGTM!
