### ISSUE TITLE
Add LSX Search & FacetWP filtering support to all the Blog archive layouts

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx#364]
### Enhancement Description 
Add filtering to the blog archives to allow readers to do a live search via a search form & filter blog post content by "Category" and "Tag" checkboxes. 

### Describe the solution you'd like
Add support to the LSX Blog Landing to allow filters with different layouts:

- [x] Blog Landing with Default Layout
- [x] Blog Landing with List Layout
- [x] Blog Landing with Grid Layout

Sidebar Filters 
- [x] Search form
- [x] Categories
- [x] Tags

**IMPORTANT:** better to the LSX theme options for all the usual LSX Search config options.

### List view - Blog Archive - List view with filters

<img alt="List view - Blog Archive - List view with filters" src="https://user-images.githubusercontent.com/31090573/84390762-54226200-abf8-11ea-9ab2-d1bb7fcc71fc.png">

Invision design - https://projects.invisionapp.com/d/main#/console/19153622/421226126/preview

### Grid view, 2 col - Blog Archive - Grid view 2col with filters

<img alt="Grid view, 2 col - Blog Archive - Grid view 2col with filters" src="https://user-images.githubusercontent.com/31090573/84390484-f3932500-abf7-11ea-94bf-005ef5415c75.png">

Invision design - https://projects.invisionapp.com/d/main#/console/19153622/421226125/preview

### Grid view, 3 col - Blog Archive - Grid view 3col with filters

<img alt="Grid view, 3 col - Blog Archive - Grid view 3col with filters" src="https://user-images.githubusercontent.com/31090573/84390496-f857d900-abf7-11ea-845f-69a95d011ea1.png">

Invision link - https://projects.invisionapp.com/d/main#/console/19153622/421226124/preview

**Comment by deonschreiber** [comment]
@viscosho Please see the screen shots attached and links to designs below:

### **List view** 
![Blog Archive - List view with filters](https://user-images.githubusercontent.com/31090573/84390762-54226200-abf8-11ea-9ab2-d1bb7fcc71fc.png)

### **Grid view, 2 col** 
![Blog Archive - Grid view 2col with filters](https://user-images.githubusercontent.com/31090573/84390484-f3932500-abf7-11ea-94bf-005ef5415c75.png)

### **Grid view, 3 col** 
![Blog Archive - Grid view 3col with filters](https://user-images.githubusercontent.com/31090573/84390496-f857d900-abf7-11ea-845f-69a95d011ea1.png)
### 
**Invision links**
- https://projects.invisionapp.com/d/main#/console/19153622/421226126/preview
- https://projects.invisionapp.com/d/main#/console/19153622/421226125/preview
- https://projects.invisionapp.com/d/main#/console/19153622/421226124/preview
