### ISSUE TITLE
Move all the vendors js and css to Bower

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/lsx#4]
The following subtasks are vendor libraries that we use, these need to be moved to the Bower.json file,  so when we "upgrade" the components we use, they automatically get upgraded as well.

Modernizer
Fitvids
Mouse Wheel
Smoothscroll
Genericons

**Comment by nandotess** [comment]
@fmdalpiaz please, let us know what do you think about this task. We can use Gulp, Bowser, or we can continue updating manually. In theory would be nice have an easy way to update the libraries.

If you think this task is too old and not necessary, please comment it and close it.

Thanks.

**Comment by nandotess** [comment]
All these libraries were removed on LSX 2.0. We are using only Bootstrap and FontAwesome. And those are base libraries, we can't update them without doing deeply tests. So this issue isn't valid anymore.
