### ISSUE TITLE
Front Page > "Front Page" Page Template > Page isn't displaying properly (#1)

### ISSUE THREAD

**Issue by nandotess** [lightspeeddevelopment/lsx#41]
When I select "Front Page" template as template from a static front page, for some reason doesn't has space between the feature image and content.

- [WP admin edition](https://www.dropbox.com/s/rbda2w0mrm9sw7w/Screenshot%202016-05-19%2015.29.15.png?dl=0);
- [Result in site](https://www.dropbox.com/s/r2jwir1zl89xys8/Screenshot%202016-05-19%2015.21.46.png?dl=0).

Let me know if is a problem in my site edition or a theme issue.

**Comment by ashleyshaw** [comment]
I feel we need to plan out the homepage better, I am closing this and making a single task for doing some design improvements.
