### ISSUE TITLE
Front Page > "Front Page" Page Template > Page isn't displaying properly (#2)

### ISSUE THREAD

**Issue by nandotess** [lightspeeddevelopment/lsx#42]
Same as #41, but with "Fixed Header" option selected (in Customizer). When the site is on top, doesn't has a margin above the image to discount the menu position:fixed. We lost a part of image, it's hidden. And now we have a huge space between the feature image and content.

- [WP admin edition](https://www.dropbox.com/s/cdq66wovjmhgxtw/Screenshot%202016-05-19%2015.34.34.png?dl=0);
* [Result in site](https://www.dropbox.com/s/vteek6vav3o4elm/Screenshot%202016-05-19%2015.32.34.png?dl=0).

Let me know if is a problem in my site edition or a theme issue.

**Comment by ashleyshaw** [comment]
Please see if you can fix this in the header.
