### ISSUE TITLE
Widgets displaying even though they aren't set

### ISSUE THREAD

**Issue by jacquesvdhorst** [lightspeeddevelopment/lsx#548]
### Describe the bug
When the LSX theme is loaded it will display default widgets on all the pages even when widgets aren't set in the customizer. A workaround at the moment is to just change the site's body width from full to side bar and then back - this removes the widgets on the pages. It might just be that the widgets are being set when the theme initalizes.

### Steps to Reproduce
1. Install LSX theme on a clean install
2. Preview any pages

### Expected behaviour
This shouldn't display. 

### Screenshots
![Screenshot_2021-01-21 About Us Zeta Tours](https://user-images.githubusercontent.com/35291167/105675921-73090680-5ef2-11eb-92eb-991bdee75db3.jpg)

### Additional context
Workaround: Changing the body layout in the customizer from full to the sidebar and then back fixes this.

**Comment by krugazul** [comment]
@jacquesvdhorst im merging this issue with #553
