### ISSUE TITLE
Mobile - Header Logo is off center 

### ISSUE THREAD

**Issue by jacquesvdhorst** [lightspeeddevelopment/lsx#562]
### Describe the bug
When in mobile size the Logo of the site will be off-centre. This is caused by the mobile menu buttons spacing. We can fix this by just adjusting some CSS rules.

### Steps to Reproduce
1. Size down website to mobile size.

### Expected behaviour
To be centred at all times.

**Comment by krugazul** [comment]
![Screenshot 2021-04-14 at 14 26 58](https://user-images.githubusercontent.com/1805603/114716696-96469380-9d34-11eb-9ba6-92f6b128bb77.png)
 The logo has been set to centre
