### ISSUE TITLE
Improve title styling when no featured image is set

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx#74]
If no featured image is set, the title be styled like the archives with a blue bar horizontal

**Comment by ashleyshaw** [comment]
![post-title-without-featured-image](https://cloud.githubusercontent.com/assets/1805352/16734489/fd180dd2-4785-11e6-8444-c5dc72bff68b.jpg)

**Comment by nandotess** [comment]
Duplicated #92.
